name: Release DevOps with Docker to Heroku

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container Registry 
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
